version: '3'
services:
  client:
    image: client
    build: .
    ports:
      - "443:443"
    restart: always
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf